// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB20QtAC16w4M0qExkhjeJlSUWHoBJQ9M0',
    appId: '1:180035550195:web:4be904cc5819ce951bf086',
    messagingSenderId: '180035550195',
    projectId: 'los-pollos-hermanos-app',
    authDomain: 'los-pollos-hermanos-app.firebaseapp.com',
    storageBucket: 'los-pollos-hermanos-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe5m_Rbcn5n1pXsHHDf6ZjT4DS0V_qdHo',
    appId: '1:180035550195:android:a24b6f5f7bb38b531bf086',
    messagingSenderId: '180035550195',
    projectId: 'los-pollos-hermanos-app',
    storageBucket: 'los-pollos-hermanos-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfxRUHQZegXGIIzETCUet2Q5wiUygnJp0',
    appId: '1:180035550195:ios:db556338c4c45c6c1bf086',
    messagingSenderId: '180035550195',
    projectId: 'los-pollos-hermanos-app',
    storageBucket: 'los-pollos-hermanos-app.appspot.com',
    iosBundleId: 'com.example.sushiRestaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfxRUHQZegXGIIzETCUet2Q5wiUygnJp0',
    appId: '1:180035550195:ios:286aba6c744de36d1bf086',
    messagingSenderId: '180035550195',
    projectId: 'los-pollos-hermanos-app',
    storageBucket: 'los-pollos-hermanos-app.appspot.com',
    iosBundleId: 'com.example.sushiRestaurantApp.RunnerTests',
  );
}
